// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toixbfalnzoaloiipksy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvaXhiZmFsbnpvYWxvaWlwa3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NTc1OTEsImV4cCI6MjA1ODQzMzU5MX0.1oX2ljamZ8AbpWXSx8FRruamR4vzU8wtzbREPoL5wdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);